### ISSUE TITLE
Telemetry is not supported when using edge runtime

### ISSUE THREAD

**Issue by sgoodluck** [auth0/nextjs-auth0#1079]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Telemetry being enabled for Next.js is not supported when using edge runtime

### Reproduction

Setup any simple application

Try to use `./pages/api/auth/[...auth0].ts` for authentication

Deploy to cloudflare pages

Observe the warning. 

<img width="922" alt="Screen Shot 2023-02-24 at 11 34 24 AM" src="https://user-images.githubusercontent.com/106334996/221234600-ac2adc34-96d2-450f-851d-76838d0124b6.png">

This occurs when the only API route is the authentication one listed above. 

### SDK version

latest/lts

### Next.js version

13.1.6

### Node.js version

16.19.1

**Trace Below**
```
▲ warn  - Compiled with warnings
▲ 
▲ 
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ A Node.js API is used (Buffer at line: 30) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/oidc-token-hash@5.0.1/node_modules/oidc-token-hash/lib/index.js
▲ A Node.js API is used (Buffer at line: 8) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/oidc-token-hash@5.0.1/node_modules/oidc-token-hash/lib/index.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/oidc-token-hash@5.0.1/node_modules/oidc-token-hash/lib/shake256.js
▲ A Node.js API is used (process.version at line: 3) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/oidc-token-hash@5.0.1/node_modules/oidc-token-hash/lib/shake256.js
▲ ./node_modules/.pnpm/oidc-token-hash@5.0.1/node_modules/oidc-token-hash/lib/index.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (process.version at line: 33) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (Buffer at line: 344) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (process.stdout at line: 1600) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (Buffer at line: 1640) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (Buffer at line: 1641) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (Buffer at line: 1642) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (Buffer at line: 1643) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.
▲ js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ A Node.js API is used (process.emitWarning at line: 1773) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/device_flow_handle.js
▲ A Node.js API is used (process.stdout at line: 118) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/device_flow_handle.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ A Node.js API is used (Buffer at line: 2) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/token_set.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ A Node.js API is used (Buffer at line: 3) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/token_set.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ A Node.js API is used (Buffer at line: 7) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/token_set.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ A Node.js API is used (Buffer at line: 10) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/base64url.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/token_set.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ A Node.js API is used (Buffer at line: 38) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/passport_strategy.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ A Node.js API is used (Buffer at line: 71) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/passport_strategy.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ A Node.js API is used (Buffer at line: 129) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/client.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/passport_strategy.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_mod
▲ info  - Collecting page data...
▲ 
▲ ules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/process_response.js
▲ A Node.js API is used (Buffer at line: 19) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/process_response.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ A Node.js API is used (Buffer at line: 53) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ A Node.js API is used (Buffer at line: 151) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ A Node.js API is used (Buffer at line: 170) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/helpers/request.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ A Node.js API is used (process.stdout at line: 197) which is not supported in the Edge Runtime.
▲ Learn more: https://nextjs.org/docs/api-reference/edge-runtime
▲ 
▲ Import trace for requested module:
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/issuer.js
▲ ./node_modules/.pnpm/openid-client@5.4.0/node_modules/openid-client/lib/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/auth0-session/index.js
▲ ./node_modules/.pnpm/@auth0+nextjs-auth0@2.2.1_next@13.1.6/node_modules/@auth0/nextjs-auth0/dist/index.js
▲ 
▲ 
```

**Comment by sgoodluck** [comment]
Update: disabling telemetry disables these errors but builds still fail when deployed to cloudfalre:

```
2023-02-24T17:29:07.160974Z	Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
  at worker.mjs:12519:51 in 6076
  at worker.mjs:1182:41 in __webpack_require__
  at worker.mjs:12453:96 in 6345
  at worker.mjs:1182:41 in __webpack_require__
  at worker.mjs:12524:133 in 8042
  at worker.mjs:1182:41 in __webpack_require__
  at worker.mjs:14418:82 in 6964
  at worker.mjs:1182:41 in __webpack_require__
  at worker.mjs:14399:17 in 534
  at worker.mjs:1182:41 in __webpack_require__

```

**Comment by adamjmcgrath** [comment]
Hi @sgoodluck - thanks for raising this

The authentication routes (/api/auth/*) on this SDK have to be run on a Node runtime, they cannot be run on the Edge runtime.

One day it would be nice to run the whole SDK on the edge runtime, but that isn't the case today - and we currently have no plans to support this at the moment.

**Comment by sgoodluck** [comment]
Roger, thank you for the reply! Updating the Readme to be explicit about this may save some devs time in the future!

**Comment by pirtlj** [comment]
Would really like to see this supported, makes sense to have this on the edge.  Seems odd that you would need the full Node runtime to just support auth use-cases.
