### ISSUE TITLE
Deployments fail with cloudflare workers

### ISSUE THREAD

**Issue by sgoodluck** [auth0/nextjs-auth0#1081]
### Checklist

- [X] The issue can be reproduced in the [sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/nextjs-auth0#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In short, deploying this auth solution cloudflare pages fails using dynamic routes and custom routes for authentication. 

I'm not sure why

### Reproduction

```
2023-02-25T04:29:07.308603Z	Error: Failed to publish your Function. Got error: Uncaught TypeError: Cannot read properties of undefined (reading 'substr')
  at worker.mjs:12531:51 in 6076
  at worker.mjs:1187:41 in __webpack_require__
  at worker.mjs:12465:96 in 6345
  at worker.mjs:1187:41 in __webpack_require__
  at worker.mjs:12536:133 in 8042
  at worker.mjs:1187:41 in __webpack_require__
  at worker.mjs:14430:82 in 6964
  at worker.mjs:1187:41 in __webpack_require__
  at worker.mjs:14411:17 in 534
  at worker.mjs:1187:41 in __webpack_require__
```

That's the output on cloudflare. Otherwise ultra simple build.
This is specific to the authentication portion of things... `/api/auth/[...auth0].ts` or using custom routes. 

### SDK version

the current one

### Next.js version

13.1.6

### Node.js version

16.19.1

**Comment by adamjmcgrath** [comment]
See https://github.com/auth0/nextjs-auth0/issues/1079#issuecomment-1446399962
