### ISSUE TITLE
Error: A valid Auth0 Domain must be provided

### ISSUE THREAD

**Issue by tonyjmartinez** [auth0/nextjs-auth0#130]
### Description
I am running into an error saying that I'm not providing a valid auth0 domain when I run `initAuth0`.

The auth0 domain I provide (`tonyjmartinez.auth0.com`) works when I run locally, but not when I deploy to `vercel`.

I tried logging the domain value I'm getting from my config so that I could make sure that the value is there in production, and I get the same value: `tonyjmartinez.auth0.com`.

I tried adding `https://` to the front but it caused a different error
```
    RequestError: getaddrinfo ENOTFOUND https
        at ClientRequest.<anonymous> (/var/task/node_modules/got/source/request-as-event-emitter.js:178:14)
        at ClientRequest.origin.emit (/var/task/node_modules/@szmarczak/http-timer/source/index.js:37:11)
```

### Reproduction

1. Clicking the login button calls `initAuth0` in my repo https://github.com/tonyjmartinez/hasura-nextjs-tutorial
2. Error shows up in production

```
15:45:42.171  
> Build error occurred
15:45:42.172  
Error: A valid Auth0 Domain must be provided
15:45:42.172  
    at Object.createInstance [as default] (/vercel/67cc0a50/node_modules/@auth0/nextjs-auth0/dist/instance.node.js:10:15)
15:45:42.172  
    at initAuth0 (/vercel/67cc0a50/node_modules/@auth0/nextjs-auth0/dist/index.js:8:46)
```

### Environment

> Please provide the following:

- Version of this library used: 0.13.0
- Other modules/plugins/libraries that might be involved: NextJS

**Comment by tonyjmartinez** [comment]
Found out that this was caused by my lack of understanding of where env variables are read from. They weren't being found correctly in `next.config.js`.

**Comment by tonyjmartinez** [comment]
Ok closed for real. It was an issue with my env variables not being what they should be
