### ISSUE TITLE
Login crashes due to next/dist/next-server/server/node-polyfill-fetch

### ISSUE THREAD

**Issue by olaven** [auth0/nextjs-auth0#134]
First of all, thanks for maintaining this library. It made using Auth0 way easier 👍 

### Description
Wen deployed to Vercel Now, calling my login-endpoint causes the error below. 
This does not occur when running locally. The second code sample includes my endpoint code. 
```
2020-06-14T13:49:48.981Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'next/dist/next-server/server/node-polyfill-fetch'\nRequire stack:\n- /var/task/.next/serverless/pages/api/auth/login.js\n- /var/task/now__launcher.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'next/dist/next-server/server/node-polyfill-fetch'","Require stack:","- /var/task/.next/serverless/pages/api/auth/login.js","- /var/task/now__launcher.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1133:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)","    at Module.load (internal/modules/cjs/loader.js:977:32)","    at Function.Module._load (internal/modules/cjs/loader.js:877:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)","    at internal/main/run_main_module.js:18:47"]}Unknown application error occurredRuntime.ImportModuleError
```
```typescript
import { NextApiRequest, NextApiResponse } from 'next'
import auth0 from '../../../auth/auth0';
import { BAD_REQUEST } from '../../../http/codes';

export default async function login(req: NextApiRequest, res: NextApiResponse) {
    try {
        await auth0.handleLogin(req, res);
    } catch (error) {
        console.error(error);
        res.status(error.status || BAD_REQUEST).end(error.message);
    }
}
```
```tsx 
<Button>
    <Link href="/api/auth/login">
        Login!
    </Link>
</Button>;
```
### Reproduction
* NextJS project 
* API route as first Typescript example, at `pages//api/auth/login`
* Above button in some frontend-page (i.e. `pages/index.tsx`

### Environment
- **Version of this library used:** `^0.13.0`
- **Version of the platform or framework used, if applicable:** Next.js, `9.4.4`
- **Other relevant versions (language, server software, OS, browser):** Deployed to Now 

Thanks for any help! 

Olav

**Comment by Widcket** [comment]
Hi @olaven, this doesn't seem like an issue with the SDK. I'll be closing this one.

**Comment by olaven** [comment]
@Widcket You're right. As far as I know, this was a problem with the runtime environment on Vercel.
Thank you for closing and sorry for not following this up.
