### ISSUE TITLE
Safari trying to download /api/auth/callback response

### ISSUE THREAD

**Issue by robertwbradford** [auth0/nextjs-auth0#1495]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are using this library with some Okta tenants, and it has been working great for the last couple years. We are now getting reports that Safari users are not able to authenticate. After signing in through the Okta, Safari is trying to _download_ the  `.../api/auth/callback` sign-in redirect and the user is not signed in. Most of the time the downloaded `callback` file is empty, but occasionally it will contain the following text:

```
invalid_grant (The authorization code is invalid or has expired.)
```

We also see the following in server logs:
```
   2023-10-16T16:59:44.11-0600 [RTR/10] OUT example.com - [2023-10-16T22:59:44.111598585Z] "GET /api/auth/login?returnTo=%2F HTTP/1.1" 302 0 497 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ... 
   2023-10-16T17:00:18.38-0600 [RTR/14] OUT example.com - [2023-10-16T23:00:18.104201452Z] "GET /api/auth/callback?code=w4f7sK6h6X_W5ztYN0ThDHxSwRKcBF_4Q1dRYYGVS_k&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vc3RhY2stbWV0cmljcy00NS5wdnUuY2YuY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcvIn0 HTTP/1.1" 302 0 56 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ... 
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR CallbackHandlerError: Callback handler failed. CAUSE: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:74:15
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR ... 4 lines matching cause stack trace ...
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:303:20) {
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR code: 'ERR_CALLBACK_HANDLER_FAILURE',
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR cause: IdentityProviderError: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at NodeClient.callback (/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:125:23)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:40:29
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:71:16
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async Object.fn (/app/node_modules/next/dist/server/next-server.js:741:37)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async Router.execute (/app/node_modules/next/dist/server/router.js:252:36)
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29) {
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR error: 'invalid_grant',
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR errorDescription: 'The authorization code is invalid or has expired.',
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR status: 400,
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR statusCode: 400,
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR openIdState: {
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR returnTo: 'https://example.com/'
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR }
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR },
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR status: 400
   2023-10-16T17:00:18.65-0600 [APP/PROC/WEB/0] ERR }
```
I'm not sure how to even debug this. I don't know if it's a problem with our Okta configuration(s) or this library. Here is a sample app configuration:

```
AUTH0_SECRET=our_secret_string
AUTH0_BASE_URL=https://example.com
AUTH0_ISSUER_BASE_URL=https://id.example.com/oauth2/default
AUTH0_CLIENT_ID=correct_client_id
AUTH0_CLIENT_SECRET=correct_client_secret
AUTH0_SCOPE="openid profile email offline_access"
```

Our `/pages/api/auth/[auth0].js`:

```js
import { handleAuth } from "@auth0/nextjs-auth0";

export default handleAuth();
```

I don't know that I am able to produce a reproduction repo, but any clues on what would cause "invalid_grant (The authorization code is invalid or has expired.)" errors to show up for only Safari users? When looking on the Okta side, we are seeing that the user successfully authenticated.

What other information would help debug? Thank you.

### Reproduction

I am not able to produce a reproduction in the sample app, but the steps we take when seeing the error:

1. In Safari, visit example.com/api/auth/login or be redirected there from a page requiring auth
2. Login with the Okta login screen
3. Safari tries to download the example.com/api/auth/callback response

We are only seeing this in Safari, and it is consistent for all users.

### nextjs-auth0 version

Tried multiple versions from 1.9–3.2.0

### Next.js version

12

### Node.js version

18

**Comment by robertwbradford** [comment]
Here is an example of what "authorize" endpoint redirect looks like: 

```
https://id.example.com/oauth2/default/v1/authorize?client_id=0oanska49hWmDztEZ357&scope=openid%20profile%20email%20offline_access&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fapi%2Fauth%2Fcallback&nonce=bdqD109NO9xov5DW1dPBRXLzuAU0UgsEcsigRixfV-8&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vc3RhY2stbWV0cmljcy00NS5wdnUuY2YuY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcvIn0&code_challenge_method=S256&code_challenge=Np9L-cD-N7358DgSnCKqPqaxYVQRpcdmJJTnejd-tQw
```

**Comment by robertwbradford** [comment]
Here is an example of what "authorize" endpoint redirect looks like:

```
https://id.example.com/oauth2/default/v1/authorize?client_id=...&scope=openid%20profile%20email%20offline_access&response_type=code&redirect_uri=https%3A%2F%2Fexample.com%2Fapi%2Fauth%2Fcallback&nonce=bdqD109NO9xov5DW1dPBRXLzuAU0UgsEcsigRixfV-8&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vc3RhY2stbWV0cmljcy00NS5wdnUuY2YuY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcvIn0&code_challenge_method=S256&code_challenge=Np9L-cD-N7358DgSnCKqPqaxYVQRpcdmJJTnejd-tQw
```

**Comment by adamjmcgrath** [comment]
Hi @robertwbradford 

> Safari is trying to download the .../api/auth/callback sign-in redirect

I'm not able to reproduce Safari trying to download the callback file with the example app, even when I force the Invalid Grant error. Couple of questions:

- Are you able to reproduce this locally?
- Can you provide a HAR file (with secrets redacted)
- Do you have any custom onError handling - the default error just logs to the console and returns an empty error response, on Safari this is a blank screen which a user might mistake for a file download.

> but occasionally it will contain the following text: invalid_grant (The authorization code is invalid or has expired.)

The error response doesn't contain any text, so I don't know how this would happen - maybe your custom error handler?

> The authorization code is invalid or has expired

This usually means you're trying to reuse the authorization code - could safari be making 2 requests instead of 1? I've seen issues where Service workers that are trying to cache pages for offline use do this for example.

**Comment by blakeplumb** [comment]
@adamjmcgrath 
This appears to happen when using HTTP 2.  On HTTP 1 everything works as expected.

**Comment by adamjmcgrath** [comment]
@blakeplumb - I'm not able to reproduce the issue on Safari and HTTP2. When the callback handler fails I'm not seeing any download happening, just the empty response and the log entry. Do you have a link that demonstrates the issue?

<img width="1253" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/c315e455-2d78-4606-bdf4-8b3d4f0b73ab">

**Comment by robertwbradford** [comment]
@adamjmcgrath We were able to get a temporary reproduction published. Are you able to reproduce with the following?

1. In a clean version of Safari, visit https://debug-safari-auth.churchofjesuschrist.org
2. Click "Login" and use the following credentials on the Okta screen:
  - username: debug@example.com
  - password: safaricallback
3. Submit, and you should see a `callback` file download instead of it loading the /api/auth/callback API route.

Here is a screen capture: 

https://github.com/auth0/nextjs-auth0/assets/15946/2d0d40a6-3cdf-473a-a31b-d324b2feb04e

Here are the server logs for this screen capture:

```
   2023-10-20T13:41:25.43-0600 [RTR/11] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-20T19:41:25.422846792Z] "GET /api/auth/me HTTP/1.1" 204 0 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-20T13:41:28.85-0600 [RTR/11] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-20T19:41:28.854409496Z] "GET /api/auth/login HTTP/1.1" 302 0 477 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-20T13:41:42.16-0600 [RTR/17] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-20T19:41:41.591279584Z] "GET /api/auth/callback?code=NOYDN836iKSqv9VavEKO0jCte3bwk6ZwmiiEEOP6-xI&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVidWctc2FmYXJpLWF1dGguY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcifQ HTTP/1.1" 302 0 49 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR CallbackHandlerError: Callback handler failed. CAUSE: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:74:15
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR ... 4 lines matching cause stack trace ...
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:303:20) {
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR code: 'ERR_CALLBACK_HANDLER_FAILURE',
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR cause: IdentityProviderError: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at NodeClient.callback (/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:125:23)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:40:29
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:71:16
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async Object.fn (/app/node_modules/next/dist/server/next-server.js:741:37)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async Router.execute (/app/node_modules/next/dist/server/router.js:252:36)
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29) {
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR error: 'invalid_grant',
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR errorDescription: 'The authorization code is invalid or has expired.',
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR status: 400,
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR statusCode: 400,
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR openIdState: { returnTo: 'https://debug-safari-auth.churchofjesuschrist.org' }
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR },
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR status: 400
   2023-10-20T13:41:42.76-0600 [APP/PROC/WEB/0] ERR }
   2023-10-20T13:41:42.76-0600 [RTR/4] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-20T19:41:42.267251593Z] "GET /api/auth/callback?code=NOYDN836iKSqv9VavEKO0jCte3bwk6ZwmiiEEOP6-xI&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVidWctc2FmYXJpLWF1dGguY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcifQ HTTP/1.1" 400 0 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
```

Here is our app's auth configuration:

```properties
AUTH0_SECRET=...
AUTH0_BASE_URL=https://debug-safari-auth.churchofjesuschrist.org
AUTH0_ISSUER_BASE_URL=https://dev-80835443.okta.com/oauth2/default
AUTH0_CLIENT_ID=...
AUTH0_CLIENT_SECRET=...
AUTH0_SCOPE="openid profile email offline_access"
AUTH0_LOGOUT=false
```

And our API route:

```js
import { handleAuth } from "@auth0/nextjs-auth0";

export default handleAuth();
```

We can log in successfully in other browsers, so that tells me the config is all correct, but are you able to replicate the download issue with Safari? I'm stumped as to what would cause it, but please let me know if you see where the issue is. Thank you!

**Comment by adamjmcgrath** [comment]
Hi @robertwbradford 

Thanks for sharing that. I'm able to reproduce the downloading issue. When I visit https://debug-safari-auth.churchofjesuschrist.org/api/auth/callback?error=foo Safari downloads an empty "callback" file.

I'm not able to reproduce it on a sample app https://app-dir-auth0-8zv4h5evv-adamjmcgrath.vercel.app/api/auth/callback?error=foo (I get a blank 400 response)

I can only assume it's something to do with your environment. Couple of suggestions:

- Perhaps the empty response is a problem, you could override the `onError` hander (see https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#customize-handlers-behavior) and add some content to the error response (like 'Error')
- I don't see any headers preventing caching on your response, perhaps you could add some caching headers

**Comment by robertwbradford** [comment]
Thank you. I can try those out. My question is more of why Safari users are getting the error in the first place. We are able to authenticate successfully with other browsers, but Safari is generating the "invalid_grant (The authorization code is invalid or has expired.)" error on the server logs. The callback download seems more like a side-effect problem. Are you able to see anything in the whole authentication flow on Safari that would cause the auth library to see the code as invalid or expired? Is Safari not setting some cookie/search param/header correctly?

**Comment by adamjmcgrath** [comment]
> My question is more of why Safari users are getting the error in the first place.
> "invalid_grant (The authorization code is invalid or has expired.)"

This error means that the callback handler has got the `code` parameter from the callback URL and tried to exchange it for tokens using https://auth0.com/docs/api/authentication#authorization-code-flow-with-pkce48

The code is invalid (perhaps it's somehow been mangled between the browser and the handler) or it's expired (you're using an old code or you're trying to reuse a code that has already been used)

When I login and the callback is downloaded, the page just stays at:

<img width="617" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/d213188d-31ee-421b-a8de-f7b6cf34876f">

At which point I'm tempted to hit refresh, which downloads the callback again - presumably when this happens I'm reusing the `code` and would expect the invalid_grant error.

Also, I'm having trouble loading https://debug-safari-auth.churchofjesuschrist.org/ intermittently in Safari (it keeps hanging)

<img width="619" alt="image" src="https://github.com/auth0/nextjs-auth0/assets/1299658/886b3860-99d7-4846-9739-21527094045b">

**Comment by robertwbradford** [comment]
Thank you for looking more. I'm not sure what is going on with the intermittent loading. I will try to find out. 

As for the invalid code, I'm not sure how to debug this :/ Looks like we will need to do some more digging. Something with the combination of Safari and HTTP/2 is causing the code to be come invalid.

**Comment by adamjmcgrath** [comment]
> As for the invalid code, I'm not sure how to debug this :/ Looks like we will need to do some more digging.

I do think that the invalid code issue is caused by user's refreshing the page after safari downloads the callback. You can confirm this by checking your tenant logs and seeing if the failed token exchange is preceded by a successful token exchange for the same user/IP using the same code. If that's the case, resolving the download issue would resolve the invalid code issue.

**Comment by robertwbradford** [comment]
Thank you, we will take a look at that.

**Comment by robertwbradford** [comment]
Looking at this again, anytime it does fail I am seeing two `GET /api/auth/callback` requests showing up in the server logs with the same `code`. For example see line 2 and 3:

```
   2023-10-27T10:49:17.80-0600 [RTR/17] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-27T16:49:17.791686658Z] "GET /api/auth/login HTTP/1.1" 302 0 477 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-27T10:49:38.74-0600 [RTR/5] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-27T16:49:38.091711794Z] "GET /api/auth/callback?code=ySZUl-viiT6pYPJs_fPuMiSqYrB7nhCCRpsX_T8MjJ0&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVidWctc2FmYXJpLWF1dGguY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcifQ HTTP/1.1" 302 0 49 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-27T10:49:39.53-0600 [RTR/19] OUT debug-safari-auth.churchofjesuschrist.org - [2023-10-27T16:49:38.960284326Z] "GET /api/auth/callback?code=ySZUl-viiT6pYPJs_fPuMiSqYrB7nhCCRpsX_T8MjJ0&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vZGVidWctc2FmYXJpLWF1dGguY2h1cmNob2ZqZXN1c2NocmlzdC5vcmcifQ HTTP/1.1" 400 0 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15" ...
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR CallbackHandlerError: Callback handler failed. CAUSE: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:74:15
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR ... 4 lines matching cause stack trace ...
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.handleRequest (/app/node_modules/next/dist/server/base-server.js:303:20) {
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR code: 'ERR_CALLBACK_HANDLER_FAILURE',
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR cause: IdentityProviderError: invalid_grant (The authorization code is invalid or has expired.)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at NodeClient.callback (/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/client/node-client.js:125:23)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:40:29
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:71:16
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async /app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:79:13
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:366:9)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:481:9)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async Object.fn (/app/node_modules/next/dist/server/next-server.js:741:37)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async Router.execute (/app/node_modules/next/dist/server/router.js:252:36)
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:365:29) {
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR error: 'invalid_grant',
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR errorDescription: 'The authorization code is invalid or has expired.',
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR status: 400,
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR statusCode: 400,
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR openIdState: { returnTo: 'https://debug-safari-auth.churchofjesuschrist.org' }
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR },
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR status: 400
   2023-10-27T10:49:39.53-0600 [APP/PROC/WEB/0] ERR }
```
Not yet sure what is causing two requests to be made, but this appears to rule out `@auth0/nextjss-auth0` being the issue being. I will close this for now and report back on anything else we find. Thanks again for your help in tracking this down.

**Comment by Sapessii** [comment]
has anyone any update on this? keep getting the double request (and consequently the error) only on responsive versione of the app

**Comment by Ojay** [comment]
I've just discovered that disabling `cross-site tracking` in Safari fixes this issue. That's not ideal, but has led me to think that maybe setting a custom domain in Auth0 will fix this security issue. Will report back either way!

Cheers

**Comment by markhotchkiss** [comment]
Following this - interestingly I get this issue on iOS only when using Chrome AND Safari

**Comment by gabriel-miranda** [comment]
@markhotchkiss iOS only has safari and skins/wrappers, so chrome on iOS still safari-powered AFAIK. I solved it on my end by doing what's proposed in this issue https://github.com/auth0/nextjs-auth0/issues/1754 but it could be different for you

**Comment by AjSchaff** [comment]
Having the same issue on safari and chrome on iOS

**Comment by blakeplumb** [comment]
> I've just discovered that disabling `cross-site tracking` in Safari fixes this issue. That's not ideal, but has led me to think that maybe setting a custom domain in Auth0 will fix this security issue. Will report back either way!
> 
> -- EDIT --
> 
> Did you get this resolved @robertwbradford ? I've tried with a custom domain but that hasn't helped. We've a site that's ready to launch and this is the only remaining issue. If you've any pointers as to how you got it resolved I'd be really grateful. Thanks!
> 
> Cheers

We solved this by disabling http2 on our site.  Not ideal, but at least allowed us to ship.

**Comment by robertwbradford** [comment]
We never found a solution and were not able to reliably determine the actual cause. However, we did find that things started working when we disabled HTTP/2. Not ideal, but at least it stopped the issue for now.
