### ISSUE TITLE
getSession() returns a json object instead of a instance of Session

### ISSUE THREAD

**Issue by chance-sematic** [auth0/nextjs-auth0#1509]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

getSession() **sometimes** returns a json object instead of a instance of Session. So the following code fails:

```
let session = await getSession();
console.log(session instanceof Session) // false
```

### Reproduction

Use the Sample app 

1. From file "app/ssr/page.jsx",  add `Session` to the import,  eg:`import { ... , Session } from '@auth0/nextjs-auth0'`

2. Modify the first part of the component function to:

```
async function SSRPage() {
    const session = await getSession();
    console.log( { debug: session instanceof Session });
    const user = session?.user;
    return (
```

Then load the page, check the log of next.js and see` [0] { debug: false }`

### Additional context

When the session can be acquired as type `Session`, I can observe that `StatelessSession.save()` goes through a call stack like this

```
 StatelessSession.save (webpack-internal:///(middleware)/../node_modules/@auth0/nextjs-auth0/dist/auth0-session/session/abstract-session.js:54:17)
    at SessionCache.save (webpack-internal:///(middleware)/../node_modules/@auth0/nextjs-auth0/dist/session/cache.js:48:33)
    at SessionCache.init (webpack-internal:///(middleware)/../node_modules/@auth0/nextjs-auth0/dist/session/cache.js:42:28)
    at async SessionCache.get (webpack-internal:///(middleware)/../node_modules/@auth0/nextjs-auth0/dist/session/cache.js:75:9)
    at async wrappedMiddleware (webpack-internal:///(middleware)/../node_modules/@auth0/nextjs-auth0/dist/helpers/with-middleware-auth-required.js:33:29)
    at async Object.middleware [as handler] (webpack-internal:///(middleware)/./src/middleware.ts:57:16)
    at async adapter (webpack-internal:///(middleware)/../node_modules/next/dist/esm/server/web/adapter.js:185:20)
    at async runWithTaggedErrors (/Users/anch/develop/tbd/nodejs/node_modules/next/dist/server/web/sandbox/sandbox.js:98:24)
    at async DevServer.runMiddleware (/Users/anch/develop/tbd/nodejs/node_modules/next/dist/server/next-server.js:1013:24)
    at async DevServer.runMiddleware (/Users/anch/develop/tbd/nodejs/node_modules/next/dist/server/dev/next-dev-server.js:247:28)
    at async DevServer.handleCatchallMiddlewareRequest (/Users/anch/develop/tbd/nodejs/node_modules/next/dist/server/next-server.js:1096:22)
    at async DevServer.handleRequestImpl (/Users/anch/develop/tbd/nodejs/node_modules/next/dist/server/base-server.js:647:32)
```

// -------------------------
when it doesn't, it goes through a call stack like this:
```
Trace
    at StatelessSession.save (webpack-internal:///(rsc)/../node_modules/@auth0/nextjs-auth0/dist/auth0-session/session/abstract-session.js:54:17)
    at set (webpack-internal:///(rsc)/../node_modules/@auth0/nextjs-auth0/dist/session/cache.js:116:24)
    at get (webpack-internal:///(rsc)/../node_modules/@auth0/nextjs-auth0/dist/session/cache.js:99:31)
    at async Object.eval [as getSession] (webpack-internal:///(rsc)/../node_modules/@auth0/nextjs-auth0/dist/session/get-session.js:10:27)
```
So if the `StatelessSession.save()` directly read the session object from the cookie and doesn't go through the `SessionCache.init()` method, it can't be created as an instance of the `Session` class. 

This doesn't make sense, because if the session object has the content of the Session class, it should be of that class. It makes some downstream processing harder if we cannot distinguish the type. 

### nextjs-auth0 version

3.1.0

### Next.js version

13.4.13

### Node.js version

20.5

**Comment by adamjmcgrath** [comment]
Thanks for raising this @chance-sematic - will investigate
