### ISSUE TITLE
V4 beta 8 - helpers (getAccessToken, getSession) don't seem to work in API routes

### ISSUE THREAD

**Issue by Brysonmk1984** [auth0/nextjs-auth0#1828]
### Checklist

- [X] The issue can be reproduced in the [nextjs-auth0 sample app](https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/nextjs-auth0#readme), [Examples](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/nextjs-auth0/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/nextjs-auth0/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/nextjs-auth0/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In the README it states that the helpers are compatible in the API routes:

> On the server, the getAccessToken(req) helper can be used in getServerSideProps, **API routes**, and middleware to get an access token to call external APIs

This hasn't been my experience though. It seems there's an issue trading the request object and getting the headers.

### Reproduction

```
// /app/api/handler

import { auth0 } from '../../../lib/auth0';

export async function apiRouteHandler(req: NextApiRequest) {
    const session = await auth0.getSession(req);
}
```

^ Calling this API route throws an error:

```
TypeError: Headers.append: "append(name, value) {
        webidl.brandCheck(this, _Headers);
        webidl.argumentLengthCheck(arguments, 2, { header: "Headers.append" });
        name = webidl.converters.ByteString(name);
        value = webidl.converters.ByteString(value);
        return appendHeader(this, name, value);
      }" is an invalid header value.
    at Auth0Client.createRequestCookies (node_modules/@auth0/nextjs-auth0/dist/server/client.js:95:24)
    at Auth0Client.getSession (node_modules/@auth0/nextjs-auth0/dist/server/client.js:56:46)
    at POST (app/api/fetch/route.ts:26:32)
    at async AppRouteRouteModule.do (webpack://next/dist/src/server/route-modules/app-route/module.ts:529:14)
    at async AppRouteRouteModule.handle (webpack://next/dist/src/server/route-modules/app-route/module.ts:658:30)
    at async doRender (node_modules/next/src/server/base-server.ts:2504:29)
    at async responseGenerator (node_modules/next/src/server/base-server.ts:3027:21)
    at async DevServer.renderToResponseWithComponentsImpl (node_modules/next/src/server/base-server.ts:3039:23)
    at async DevServer.renderPageComponent (node_modules/next/src/server/base-server.ts:3597:15)
    at async DevServer.renderToResponseImpl (node_modules/next/src/server/base-server.ts:3659:23)
    at async DevServer.pipeImpl (node_modules/next/src/server/base-server.ts:1698:20)
    at async NextNodeServer.handleCatchallRenderRequest (node_modules/next/src/server/next-server.ts:1034:6)
    at async DevServer.handleRequestImpl (node_modules/next/src/server/base-server.ts:1462:8)
    at async (node_modules/next/src/server/dev/next-dev-server.ts:514:13)
    at async Span.traceAsyncFn (node_modules/next/src/trace/trace.ts:143:13)
    at async DevServer.handleRequest (node_modules/next/src/server/dev/next-dev-server.ts:512:19)
    at async invokeRender (node_modules/next/src/server/lib/router-server.ts:284:10)
    at async handleRequest (node_modules/next/src/server/lib/router-server.ts:530:15)
    at async requestHandlerImpl (node_modules/next/src/server/lib/router-server.ts:576:6)
    at async Server.requestListener (node_modules/next/src/server/lib/start-server.ts:146:6)
  93 |             }
  94 |             else {
> 95 |                 headers.append(key, req.headers[key] ?? "");
     |                        ^
  96 |             }
  97 |         }
  98 |         return new RequestCookies(headers);
```

### nextjs-auth0 version

4.0.0-beta.8

### Next.js version

15.0.3

### Node.js version

v21.7.1

**Comment by guabu** [comment]
Hey @Brysonmk1984 👋 It looks like you're using the App Router based on the path you shared in your reproduction.

In that case, you should not be passing the `req` object as shown in this example: https://github.com/auth0/nextjs-auth0/tree/v4?tab=readme-ov-file#on-the-server-app-router

In the app router, the SDK can read the cookies directly via the `cookies()` helper method from Next.js so passing the `req` object is not necessary.

**Comment by Brysonmk1984** [comment]
Got it! Thanks @guabu . My mistake.
