### ISSUE TITLE
TypeError: "session.cookieSecret"(and other options) is not allowed

### ISSUE THREAD

**Issue by xxbxxqxx** [auth0/nextjs-auth0#366]
Hi, this may be a very basic question though, I'd appreciate if I could get some advice.

### Describe the problem
Encountered the TypeError when opened http://localhost:3000/.
![Screenshot 2021-04-11 at 22 40 27](https://user-images.githubusercontent.com/9583157/114320605-eb0cc300-9b16-11eb-8c79-0971382a6647.png)

console logs here:

```
TypeError: "session.cookieSecret" is not allowed
    at Object.get (~/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:145:15)
    at Object.getConfig (~/app/node_modules/@auth0/nextjs-auth0/dist/config.js:39:40)
    at initAuth0 (~/app/node_modules/@auth0/nextjs-auth0/dist/index.js:22:49)
    at eval (webpack-internal:///./src/pages/api/utils/auth0.js:5:126)
    at Object../src/pages/api/utils/auth0.js (~/app/.next/server/pages/index.js:22:1)
    at __webpack_require__ (~/app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./src/pages/index.js:12:74)
    at Object../src/pages/index.js (~/app/.next/server/pages/index.js:33:1)
    at __webpack_require__ (~/app/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (~/app/.next/server/pages/index.js:86:52)
    at ~/app/.next/server/pages/index.js:87:28
    at Object.<anonymous> (~/app/.next/server/pages/index.js:90:3)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
```

### Reproduction

- Step 1. `npm init next-app sample-auth0-app`
- Step 2. `npm install @auth0/nextjs-auth0`
- Step 3. Create the Auth0 client configuration with auth0.js as below:

src/pages/api/utils/auth0.js
```
import { initAuth0 } from '@auth0/nextjs-auth0';

export default initAuth0({
  domain: process.env.AUTH0_DOMAIN,
  clientId: process.env.AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_SECRET,
  redirectUri: 'http://localhost:3000/api/callback',
  postLogoutRedirectUri: 'http://localhost:3000/',
  session: {
      cookieSecret: process.env.COOKIE_SECRET,
  },
});
```

- Step 4. Change index.js

src/pages/index.js
```
...
import auth0 from './api/utils/auth0';

export default function Home({ user }) {
    return ( ... )
}

export async function getServerSideProps(context) {
    const session = await auth0.getSession(context.req);
    let todos = await table.select().firstPage();
    return {
        props: {
            initialTodos: minifyRecords(todos),
            user: session?.user || null,
        },
    };
}
```
(These steps are referred to https://www.jamesqquick.com/blog/authenticated-jamstack-app-with-next-js-airtable-auth0-and-tailwind-css)

Then I encountered the error.

If I comment out the `cookieSecret` line then it shows the same TypeError as below;
```TypeError: "domain" is not allowed```

### Environment

- 'node -v' v15.3.0 (I tried v14.15.0 as well)
- `.env` is already set
- "@auth0/nextjs-auth0": "^1.2.0",
- "next": "10.1.3",
- "react": "17.0.2",
- "react-dom": "17.0.2"
- in `next.config.js` webpack 5 is specified 
```
module.exports = {
  future: { webpack5: true }
}
```

Thanks.

**Comment by lsbyerley** [comment]
Running into this as well for the `"session.cookieSecret" is not allowed` error

**Comment by adamjmcgrath** [comment]
Hi @xxbxxqxx and @lsbyerley - the [article](https://www.jamesqquick.com/blog/authenticated-jamstack-app-with-next-js-airtable-auth0-and-tailwind-css) @xxbxxqxx is referring to uses the 0.x version of the SDK.

In the current 1.x version `session.cookieSecret` is now `secret`, see the [1.x Migration guide](https://github.com/auth0/nextjs-auth0/blob/main/V1_MIGRATION_GUIDE.md) for more details

**Comment by lsbyerley** [comment]
@adamjmcgrath thanks for pointing this out. Solved my issues

**Comment by adamjmcgrath** [comment]
No problem @lsbyerley

**Comment by xxbxxqxx** [comment]
@adamjmcgrath Thanks for the answer, it's solved.
