### ISSUE TITLE
handleCallback - Cannot read property 'toString' of undefined error

### ISSUE THREAD

**Issue by lsbyerley** [auth0/nextjs-auth0#371]
### Description

> After authenticating with auth0 and being redirected back to `/api/callback` a `Cannot read property 'toString' of undefined` error is generated in the callback

### Reproduction

The description basically says it all. This is what my `/api/callback` file looks like. 

my auth0 instance file:
```
const auth0Instance = initAuth0({
  baseURL: config.BASE_URL,
  clientID: config.AUTH0_CLIENT_ID,
  clientSecret: config.AUTH0_CLIENT_SECRET,
  secret: config.SESSION_SECRET,
  issuerBaseURL: config.AUTH0_ISSUER_BASE_URL,
  authorizationParams: {
    scope: config.AUTH0_SCOPE,
  },
  routes: {
    callback: config.CALLBACK_URI,
    postLogoutRedirectUri: config.POST_LOGOUT_REDIRECT_URI,
  },
  session: {},
});
```

```
import auth0 from '@/lib/auth0';

const callback = async (req, res) => {
  try {
    await auth0.handleCallback(req, res);
  } catch (error) {
    console.error(error);
    res.status(error.status || 500).end(error.message);
  }
};

export default callback;
```

The stacktrace seems to point to this decodeState function in callback.ts
https://github.com/auth0/nextjs-auth0/blob/bc11293acb242118db19c2ca84159d6778b25404/src/auth0-session/handlers/callback.ts#L53

```
at Object.decodeState (/node_modules/@auth0/nextjs-auth0/dist/auth0-session/hooks/get-login-state.js:47:43)
    at Object.<anonymous> (/node_modules/@auth0/nextjs-auth0/dist/auth0-session/handlers/callback.js:32:47)
```

Does anyone know what could be causing this?

UPDATE:
If, i pass in the `redirectUri` to `handleCallback()` like so..
```
await auth0.handleCallback(req, res, { redirectUri: '/' });
```

I get a different error: "unauthorized_client (The redirect URI is wrong. You sent null//null, and we expected http://localhost:3000)" could that mean something is amiss in the config?

### Environment

> Please provide the following:

- **Version of this library used:** 1.3.0
- **Version of the platform or framework used, if applicable:** NextJS v10.1.3
- **Other relevant versions (language, server software, OS, browser):** chrome v87
- **Other modules/plugins/libraries that might be involved:**

**Comment by lsbyerley** [comment]
I've been setting the api urls using the old way of `/api/login`, `/api/callback`, etc.

After adding the `/api/auth/[...auth0].js` route.. things are working as expected. I must have followed an older tutorial.
