### ISSUE TITLE
Error [TypeError]: Invalid character in header content [&quot;Location&quot;]

### ISSUE THREAD

**Issue by srbagg** [auth0/nextjs-auth0#461]
### Describe the problem
After successful login the nextjs-auth0 callback handler is throwing the below error:
```
Error [TypeError]: Invalid character in header content [&quot;Location&quot;]
    at new HandlerError (/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:49:28)
    at Object.<anonymous> (/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:39:31)
    at step (node_modules/tslib/tslib.js:143:27)
    at Object.throw (/node_modules/tslib/tslib.js:124:57)
    at rejected (/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: 'ERR_INVALID_CHAR'
```

**Note:** This error is thrown only when running the production environment build. Development environment is working as expected without any errors.

### What was the expected behavior?
Should work without throwing error.

### Reproduction

- Followed the [Readme.md](https://github.com/auth0/nextjs-auth0) with custom BasePath configuration

### Environment

- **Version of this library used:** ^1.5.0
- **Which framework are you using, if applicable:** next@^11.0.1, react^17.0.2
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by srbagg** [comment]
Able to reproduce this error in development environment as well. Stack trace:
```
Error [BadRequestError]: checks.state argument is missing
    at new HandlerError (/node_modules/@auth0/nextjs-auth0/src/utils/errors.ts:52:5)
    at Object.<anonymous> (/node_modules/@auth0/nextjs-auth0/src/handlers/callback.ts:133:13)
    at step (/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/node_modules/tslib/tslib.js:124:57)
    at rejected (/node_modules/tslib/tslib.js:115:69)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  status: 400
}
```

**Comment by Widcket** [comment]
Hi @srbagg, thanks for raising this. The SDK [uses](https://github.com/auth0/nextjs-auth0/blob/main/src/auth0-session/handlers/callback.ts#L63) the Location header to perform a redirect:
```js
    res.writeHead(302, {
      Location: openidState.returnTo || config.baseURL
    });
```
Are you passing a custom `returnTo` to the login handler? Does it contain any character that may be triggering this error? What about your `baseURL`?

**Comment by srbagg** [comment]
Thanks @Widcket for pointing in right direction. My app was using custom `returnTo` value and found out that that there was some issue with `returnTo` path that was computed in my application. After resolving it, this issue went away. Hence closing this issue.
Thanks you!
