### ISSUE TITLE
Error thrown in /callback when using the Auth0 account link extension

### ISSUE THREAD

**Issue by bguthrie** [auth0/nextjs-auth0#501]
### Description

The nextjs-auth0 library appears to be throwing the following exception when my users attempt to merge a social account login with a password login:

```
[GET] /api/auth/callback?code=...&state=...
11:36:53:09
ERROR	Error [BadRequestError]: checks.state argument is missing
    at new HandlerError (/var/task/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:49:28)
    at Object.<anonymous> (/var/task/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:39:31)
    at step (/var/task/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:143:27)
    at Object.throw (/var/task/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:124:57)
    at rejected (/var/task/node_modules/@auth0/nextjs-auth0/node_modules/tslib/tslib.js:115:69)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  status: 400
}
```

### Reproduction

My app is in private beta, so users cannot create their own account. To invite users, I'm creating a new user account on their behalf, following the instructions documented here: https://auth0.com/docs/brand-and-customize/email/send-email-invitations-for-application-signup

1. User clicks on the welcome email and changes their password using the base Auth0 login flow.
2. After subsequently changing their password, user clicks the Login with Google button, which triggers the Auth0 account link extension.
3. User is then prompted to merge accounts, which in turn prompts them to re-enter their password to continue.
4. After re-entering their password, the above error is thrown.

### Environment

> Please provide the following:

- **Version of this library used:** 1.5.0
- **Version of the platform or framework used, if applicable:** NextJS 10.2.0
- **Other relevant versions (language, server software, OS, browser):** Typescript, Vercel deployment
- **Other modules/plugins/libraries that might be involved:** None that I'm aware of

**Comment by bguthrie** [comment]
Deleting as it appears to have been caused by a misconfiguration in the rule. Still, no idea why this particular exception would be thrown.
