### ISSUE TITLE
Auth0 login fails with "TypeError: "secret" is required"

### ISSUE THREAD

**Issue by sajid-dev** [auth0/nextjs-auth0#526]
### Description
I have followed the Auth0 for Next.js instructions. This is not working locally either.

```
TypeError: "secret" is required
    at Object.get (/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
    at Object.getConfig (/app/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
    at Object.initAuth0 (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
    at getInstance (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at getSession (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:60:18)
    at Object.<anonymous> (/app/node_modules/@auth0/nextjs-auth0/dist/helpers/with-page-auth-required.js:23:35)
    at step (/app/node_modules/tslib/tslib.js:143:27)
    at Object.next (/app/node_modules/tslib/tslib.js:124:57)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

### Reproduction
```
export default initAuth0({
  clientID: authCid,
  clientSecret: 'val',
  secret: 'val',
  baseURL: 'val',
  issuerBaseURL: 'val',
  httpTimeout: 'val',
  authorizationParams: {
    response_type: 'code',
    scope: 'val'
  },
  session: {
    name: 'val',
    rollingDuration: 'val'
  }
});


import auth0 from '../../../lib/auth0';
export default auth0.handleAuth();

```
I am creating my own instance by passing values manually. I am not setting any environment variable
are AUTH0_SECRET, and AUTH0_CLIENT_SECRET are required even if I use to create an instance
```
"@auth0/nextjs-auth0": "1.6.1",
 "next": "11.1.2",
```

**Comment by sajid-dev** [comment]
I used withPageAuthRequired in index.js

```
import Head from 'next/head'
import Image from 'next/image'
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

export default function Home() {
  return (
   <div>test</div>
  )
}

export const getServerSideProps = withPageAuthRequired();
```

**Comment by adamjmcgrath** [comment]
Hi @sajid-dev 

If you initialize your own instance of the SDK with `initAuth0` - you need to use the server methods from that instance. eg

```js
const auth0 = initAuth0();

const { withPageAuthRequired } = auth0;
```

You can't mix instance methods and named exports (when you use named exports, we create an instance for you using your environment variables) - see https://auth0.github.io/nextjs-auth0/modules/config.html#2-create-your-own-instance-using-initauth0 for more info

**Comment by sajid-dev** [comment]
It works now thanks a lot for taking your time and finding my mistake
