### ISSUE TITLE
withApiAuthRequired Object(...) is not a function

### ISSUE THREAD

**Issue by chalupagrande** [auth0/nextjs-auth0#540]
```
// src/pages/api/test.js

import { withApiAuthRequired, getSession } from '@auth0/nextjs-auth0'

export default withApiAuthRequired(async function ProtectedRoute(req, res) {
  const session = getSession(req, res)
  res.send('ok')
})
```

I get the following error: 
```
TypeError: Object(...) is not a function
    at eval (webpack-internal:///./src/pages/api/test.js:6:143)
    at Module../src/pages/api/test.js (/<PROJECT_PATH>/.next/server/pages/api/test.js:104:1)
    at __webpack_require__ (/<PROJECT_PATH>/.next/server/pages/api/test.js:23:31)
    at /<PROJECT_PATH>/.next/server/pages/api/test.js:91:18
    at Object.<anonymous> (/<PROJECT_PATH>/.next/server/pages/api/test.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at DevServer.handleApiRequest (/<PROJECT_PATH>/node_modules/next/dist/next-server/server/next-server.js:64:181)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.fn (/<PROJECT_PATH>/node_modules/next/dist/next-server/server/next-server.js:56:492)
    at async Router.execute (/<PROJECT_PATH>/node_modules/next/dist/next-server/server/router.js:23:67)
```

relevant package.json
```
"dependencies": {
    "@apollo/client": "^3.3.6",
    "@auth0/nextjs-auth0": "^0.16.1",
    "auth0": "^2.34.2",
    "http-proxy-middleware": "^1.0.6",
    "next": "10.0.7",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "webpack": "^4.46.0"
  },
```

relevant documentation: https://auth0.github.io/nextjs-auth0/modules/helpers_with_api_auth_required.html

**Comment by chalupagrande** [comment]
I had a version mismatch! Apologies. Closing the issue.
