### ISSUE TITLE
get-config.js requires secret after production deployment with Docker

### ISSUE THREAD

**Issue by philharmonie** [auth0/nextjs-auth0#577]
### Description

Following the auth0 quick start for next.js is working on my local dev host 100%. When I deploy the app, it is missing the secret.

### Reproduction

I added Auth0 to my next.js app following the Quick Start, by creating the `.env.local` file like:
```
AUTH0_SECRET='my secret'
AUTH0_BASE_URL='http://localhost:3000'
AUTH0_ISSUER_BASE_URL='https://dev-abc123.xx.auth0.com'
AUTH0_CLIENT_ID='myclientid'
AUTH0_CLIENT_SECRET='myclientsecret'
```

I added the `handleAuth()` to the api route and I added the `UserProvider`. With that, I can login and logout. Everything is working so far on my local dev host.

Now I add this app the my Server and create a `Dockerfile`:
```
FROM node:16-alpine AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:16-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN yarn build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

ENV NEXT_TELEMETRY_DISABLED 1

CMD ["node", "server.js"]
```
When I now build the app and run it, I get the following error:

```
Listening on port 3000
TypeError: "secret" is required
    at Object.get (/app/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
    at Object.getConfig (/app/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
    at Object.initAuth0 (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
    at getInstance (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at getSession (/app/node_modules/@auth0/nextjs-auth0/dist/index.js:60:18)
    at Object.<anonymous> (/app/node_modules/@auth0/nextjs-auth0/dist/helpers/with-page-auth-required.js:23:35)
    at step (/app/node_modules/tslib/tslib.js:143:27)
    at Object.next (/app/node_modules/tslib/tslib.js:124:57)
    at /app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
```

### Environment

- "@auth0/nextjs-auth0": "^1.7.0",
- "next": "^12.0.7"
- Docker version 20.10.12, build e91ed57
- Server runs Ubuntu 20.04
- node v16.13.2

**Comment by philharmonie** [comment]
Needed to add `COPY --from=builder /app/.env.production ./`
