### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'auth0') On logout?

### ISSUE THREAD

**Issue by rikkertkoppes** [auth0/nextjs-auth0#658]
### Description

My application occasionally exits with the following error, which seems to happen when navigating to `/api/auth/logout`, but only in a built context (not during development):

```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Promise%5D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at O (/usr/src/app/node_modules/react/cjs/react.production.min.js:17:207)
    at P (/usr/src/app/node_modules/react/cjs/react.production.min.js:17:355)
    at toArray (/usr/src/app/node_modules/react/cjs/react.production.min.js:19:177)
    at a.b.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:249)
    at a.b.read (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
    at Object.renderPage (/usr/src/app/node_modules/next/dist/server/render.js:768:45)
    at Object.defaultGetInitialProps (/usr/src/app/node_modules/next/dist/server/render.js:375:51)
    at Function.getInitialProps (/usr/src/app/.next/server/chunks/859.js:566:20)
    at Object.loadGetInitialProps (/usr/src/app/node_modules/next/dist/shared/lib/utils.js:65:29)
/usr/src/app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:38
                route = req.query.auth0;
                                  ^

TypeError: Cannot read properties of undefined (reading 'auth0')
    at Object.<anonymous> (/usr/src/app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:38:35)
    at step (/usr/src/app/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/src/app/node_modules/tslib/tslib.js:124:57)
    at /usr/src/app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/src/app/node_modules/tslib/tslib.js:113:16)
    at /usr/src/app/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:35:53
    at d (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
    at bb (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
    at a.b.render (/usr/src/app/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
```

The line, when compiled reads as:

```js
route = req.query.auth0;
```

The original code is found here: https://github.com/auth0/nextjs-auth0/blob/main/src/handlers/auth.ts#L103

I am not sure why `req.query` should ever be undefined, my [...auth0] api page contains the following:

```
import { handleAuth, handleCallback } from "@auth0/nextjs-auth0";

const afterCallback = async (req, res, session, state) => {
    let user = session.user;
    // store user
    console.log("store user", user);
    return session;
};

export default handleAuth({
    async callback(req, res) {
        try {
            await handleCallback(req, res, { afterCallback });
        } catch (error) {
            res.status(error.status || 500).end(error.message);
        }
    },
});

```

### Environment

using 
- nextjs-auth0@1.7.0
- nextjs@12.1.4

all in a dockerized node:16-alpine3.15 image

**Comment by rikkertkoppes** [comment]
Was investigating a bit more while trying to come up with a minimal example.

Turns out using nextjs `useRouter` to logout was the culprit. On logout button click I was using

```
router.push('/api/auth/logout');
```

after changing this to 

```
location.assign('/api/auth/logout');
```

there were no more errors.

path of the auth route was indeed `/pages/api/auth/[...auth0].js`

**Comment by adamjmcgrath** [comment]
Ah ok, thanks for confirming @rikkertkoppes - yep, you need to use regular links when linking to api routes in next
