### ISSUE TITLE
Getting "invalid algorithm" when querying API

### ISSUE THREAD

**Issue by BjoernRave** [auth0/nextjs-auth0#71]
When trying to authenticate my requests against my API, I keep getting the following error:

```
[CombinedError: [Network] undefined] {
  name: 'CombinedError',
  message: '[Network] undefined',
  graphQLErrors: [
    GraphQLError: invalid algorithm
        at rehydrateGraphQlError (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/index-dddbd19e.js:23:12)
        at Array.map (<anonymous>)
        at new CombinedError (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/index-dddbd19e.js:39:61)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:524:30
        at _ref3 (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:531:6)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:759:56
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
        at Array.forEach (<anonymous>)
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:492:42
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
        at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
        at Array.forEach (<anonymous>)
        at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77) {
      message: 'invalid algorithm'
    }
  ],
  networkError: Error: undefined
      at /Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:525:25
      at _ref3 (/Users/bjoern/projects/inventhora/frontend/node_modules/urql/dist/cjs/core.js:531:6)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:759:56
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
      at Array.forEach (<anonymous>)
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:492:42
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14)
      at Array.forEach (<anonymous>)
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:864:77)
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:760:16
      at /Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:748:28
      at b (/Users/bjoern/projects/inventhora/frontend/node_modules/wonka/dist/wonka.js:865:14),
  response: undefined
}
```
My setup on Auth0 is one application, which is my frontend and one API, which is my backend. On the frontend I used the identifier of the API as audience. 

My application settings:
<img width="1440" alt="Screenshot 2020-01-27 at 11 53 53" src="https://user-images.githubusercontent.com/36173920/73173108-7f4e5e00-40fc-11ea-98ab-d6ace8a60dbe.png">

I also created a minimal reproducible example of my application: https://github.com/BjoernRave/Auth0-Urql-Nextjs-Prisma2

### Environment

> Please provide the following:

- Library Version: 0.10
- React Version: 16.12
- Next Version: 9.2.1

**Comment by BjoernRave** [comment]
still waiting...

**Comment by BjoernRave** [comment]
I was able to fix the problem thanks to @BryceAMcDaniel 
It was actually not an error caused by auth0, but something else in my code
