### ISSUE TITLE
auth0-nextjs SDK: Base URL not being propagated to custom handleCallback endpoint in staging only

### ISSUE THREAD

**Issue by yaacov-commenda** [auth0/nextjs-auth0#725]
> Provide a clear and concise description of the issue, including what you expected to happen.

### Reproduction

I set my baseUrl parameter with the following logic: 

```
// utils/auth0.ts

import { initAuth0 } from '@auth0/nextjs-auth0';

const { VERCEL_URL, AUTH0_BASE_URL } = process.env;
const baseURL = AUTH0_BASE_URL ?? VERCEL_URL ?? 'http://localhost:3000';

export default initAuth0({
  baseURL: !/^https?:\/\//.test(baseURL) ? `https://${baseURL}` : baseURL,
});
```

When I log the baseURL parameter, it shows the correct url for the staging deployment. 

I'm attempting to add a custom callback to auth0.handleAuth, as so: 
```
// pages/api/auth/[...auth0].ts

import { handleCallback } from '@auth0/nextjs-auth0';
import auth0 from 'utils/auth0';

export default auth0.handleAuth({
  callback: async (req, res) => {
    await handleCallback(req, res, {
      afterCallback: async (_req, _res, session, state) => {
        // state.signup is set by a method that calls handleLogin with the getLoginState callback
        if (state.signup) {
              // TODO:  initialize user. 
        }
        return session;
      },
    });
  },
});
```

When I try to log in, I get a 500 error from the `/api/auth/callback` endpoint. I see the following error in my Vercel server logs: 
```
[GET] /api/auth/callback?code=mdxyBRu9K4C89DoMs-a2fMcFjq3kZ7ifVHPmEQrVqkQ7R&state=eyJyZXR1cm5UbyI6Imh0dHBzOi8vY29tbWVuZGEtYmxvbGQwOWd5LWNvbW1lbmRhLnZlcmNlbC5hcHAvIn0
21:21:18:80
2022-06-09T04:21:18.864Z	7b52258a-b223-49b6-a412-c7a111c23206	ERROR	TypeError: "baseURL" is required
    at Object.get (/var/task/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
    at Object.getConfig (/var/task/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
    at Object.initAuth0 (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
    at getInstance (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at handleCallback (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:106:18)
    at callback (/var/task/.next/server/pages/api/auth/[...auth0].js:38:82)
    at Object.<anonymous> (/var/task/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:46:47)
    at step (/var/task/node_modules/tslib/tslib.js:143:27)
    at Object.next (/var/task/node_modules/tslib/tslib.js:124:57)
    at /var/task/node_modules/tslib/tslib.js:117:75
2022-06-09T04:21:18.864Z	7b52258a-b223-49b6-a412-c7a111c23206	ERROR	TypeError: "baseURL" is required
    at Object.get (/var/task/node_modules/@auth0/nextjs-auth0/dist/auth0-session/get-config.js:147:15)
    at Object.getConfig (/var/task/node_modules/@auth0/nextjs-auth0/dist/config.js:66:38)
    at Object.initAuth0 (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:22:23)
    at getInstance (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:18:24)
    at handleCallback (/var/task/node_modules/@auth0/nextjs-auth0/dist/index.js:106:18)
    at callback (/var/task/.next/server/pages/api/auth/[...auth0].js:38:82)
    at Object.<anonymous> (/var/task/node_modules/@auth0/nextjs-auth0/dist/handlers/auth.js:46:47)
    at step (/var/task/node_modules/tslib/tslib.js:143:27)
    at Object.next (/var/task/node_modules/tslib/tslib.js:124:57)
    at /var/task/node_modules/tslib/tslib.js:117:75
RequestId: 7b52258a-b223-49b6-a412-c7a111c23206 Error: Runtime exited with error: exit status 1
Runtime.ExitError

```

This issue only occurs in my Vercel staging deployments. It does not occur in my local development environment (next server at http://localhost:3000), and it does not occur in my Vercel production deployment. 

When I comment out the custom `callback` the issue goes away.

This issue is superficially similar to https://github.com/auth0/nextjs-auth0/issues/420, but it occurs _even when baseURL is set correctly_ when a custom `callback` is used .

### Environment

> Please provide the following:

- **Version of this library used:**
-    "@auth0/nextjs-auth0": "^1.7.0",
- **Other relevant versions (language, server software, OS, browser):**
- Next.js, (browser is chrome on macos, not that that should matter).  

Thanks in advance for your help!!

**Comment by adamjmcgrath** [comment]
Hi @yaacov-commenda - thanks for raising this

> `import { handleCallback } from '@auth0/nextjs-auth0';`

I see you're creating your own instance and importing a named export. You can't mix these, if you're creating your own instance, you should always use `instance.handleCallback` rather than importing the named export 

See https://auth0.github.io/nextjs-auth0/modules/config.html#2-create-your-own-instance-using-initauth0 for more info

**Comment by yaacov-commenda** [comment]
That was it, thank you!!!
