### ISSUE TITLE
Error trying to sign in after quick setup

### ISSUE THREAD

**Issue by RedFour** [auth0/nextjs-auth0#738]
### Description

After signing in, I should be taken back to the home page. Instead I'm getting an error message.

### Reproduction

I've following along the Next.js Auth0 quirkstart guide, and cloned https://github.com/auth0-samples/auth0-nextjs-samples/tree/main/Sample-01. In both attempts, I'm met with the following error once I tried to sign in

Terminal:
```
HandlerError [BadRequestError]: access_denied (Compilation failed: Must use import to load ES Module: /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/src/index.js from /data/io/node16/d7c9ec22-c745-4b80-b36b-82dc794228b6/webtask.js is an ES module file as it is a .js file whose nearest parent package.json contains &quot;type&quot;: &quot;module&quot; which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove &quot;type&quot;: &quot;module&quot; from /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/package.json.
)
    at new HandlerError (/home/dachyan/projects/stuffdb/stuffdb-web-nextjs/node_modules/@auth0/nextjs-auth0/dist/utils/errors.js:53:28)
    at Object.<anonymous> (/home/dachyan/projects/stuffdb/stuffdb-web-nextjs/node_modules/@auth0/nextjs-auth0/dist/handlers/callback.js:39:31)
    at step (/home/dachyan/projects/stuffdb/stuffdb-web-nextjs/node_modules/tslib/tslib.js:144:27)
    at Object.throw (/home/dachyan/projects/stuffdb/stuffdb-web-nextjs/node_modules/tslib/tslib.js:125:57)
    at rejected (/home/dachyan/projects/stuffdb/stuffdb-web-nextjs/node_modules/tslib/tslib.js:116:69)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 400
}
```

Web:
```
access_denied (Compilation failed: Must use import to load ES Module: /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/src/index.js from /data/io/node16/a78f1cbd-d897-44f9-809e-ed02ea4b3316/webtask.js is an ES module file as it is a .js file whose nearest parent package.json contains &quot;type&quot;: &quot;module&quot; which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove &quot;type&quot;: &quot;module&quot; from /data/layers/layers-I_sb/I_sb-FVtOzbV4758cJH9MSJk6BRSMLGpqlzpcNoAdok/node_modules/node-fetch/package.json.
)
```

### Environment
"@auth0/nextjs-auth0": "^1.9.1",
    "next": "12.1.6",

**Comment by adamjmcgrath** [comment]
Hi @RedFour - that error looks like it's coming from the Authorization server.

Do you have a Rule/Action configured that could be causing that error?

**Comment by adamjmcgrath** [comment]
Closing due to inactivity - happy to reopen if you want to provide information about how any rules/actions are configured

**Comment by RedFour** [comment]
Thank you. I was able resolve the issue by removing an action I didn't realize was being applied. I'm very new to auth0 and I thought flows were application specific.
