### ISSUE TITLE
account-link extension causes "OPError: access_denied (Cannot read property 'email' of null)"

### ISSUE THREAD

**Issue by nodabladam** [auth0/nextjs-auth0#95]
If I enable this extension in auth0, https://auth0.com/docs/extensions/account-link, I get this error when creating new users:
```
 OPError: access_denied (Cannot read property 'email' of null)
```
The user is created in auth0, but this error is thrown in the callback.

If I disable account-link extension in /dashboard/us/`<tenant>`/rules, new users can be created again.

The user is created in the auth0 interface but seems stuck.
Not sure if this helps but if I manually set user email to verified, it seems to continue on:

![image](https://user-images.githubusercontent.com/57159187/78315708-a8330b00-7512-11ea-9e58-22f896e7cdcd.png)

Using the "link-users-by-email" rule also fails with the same error. 
https://auth0.com/rules/link-users-by-email

### Environment

> Please provide the following:

- **Version of this library used: 11
- **Version of the platform or framework used, if applicable: Next.js 9.3.4
- **Other relevant versions (language, server software, OS, browser): Windows Chrome
- **Other modules/plugins/libraries that might be involved: Account Link (https://auth0.com/docs/extensions/account-link)

Full Error
 
```
 OPError: access_denied (Cannot read property 'email' of null)
     at Client.callback (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\openid-client\lib\client.js:418:13)
     at Object.<anonymous> (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\@auth0\nextjs-auth0\dist\handlers\callback.js:24:39)
     at Generator.next (<anonymous>)
     at fulfilled (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\node_modules\tslib\tslib.js:107:62)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   error: 'access_denied',
   error_description: "Cannot read property 'email' of null",
   state: '/'
 }
 Error: OPError: access_denied (Cannot read property 'email' of null)
     at callback (C:\Users\enalm\code\nodabl\nodabl-app\packages\frontend-v2\.next\server\static\development\pages\api\callback.js:193:67)
     at runMicrotasks (<anonymous>)
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by nodabladam** [comment]
Anyone else successfully able to use "link-users-by-email" rule?

**Comment by nodabladam** [comment]
Turns out this was my fault.  We had a variation of forcing email verified rule enabled (https://auth0.com/rules/email-verified) which was causing a null to be sent along.  After disable that rule everything works.
